classroom/urls.py
from django.urls import path
from .views import (ContactFormView, HomeView,ThankYouView,
                    TeacherCreateView,TeacherListView,
                    TeacherDetailView,TeacherUpdateView,TeacherDeleteView)
                    
app_name='classroom'
#domain.com/classroom/teacher_detail/1
urlpatterns = [
    path('',HomeView.as_view(),name='home'),
    path('thank_you/',ThankYouView.as_view(),name='thank_you'),
    path('contact/',ContactFormView.as_view(),name='contact'),
    path('create_teacher/',TeacherCreateView.as_view(),name='create_teacher'),
    path('list_teacher/',TeacherListView.as_view(),name='list_teacher'),
    path('teacher_detail/<int:pk>',TeacherDetailView.as_view(),name='detail_teacher'),
    path('update_teacher/<int:pk>',TeacherUpdateView.as_view(),name='update_teacher'),
    path('delete_teacher/<int:pk>',TeacherDeleteView.as_view(),name='delete_teacher'),
]

school/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classroom/',include('classroom.urls'))
]

classroom/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    first_name=models.CharField(max_length=30)
    last_name=models.CharField(max_length=30)
    subject=models.CharField(max_length=30)

    def __str__(self):
        return f"{self.first_name} {self.last_name} teaches {self.subject} subject."
    

classroom/forms.py
from django import forms

class ContactForm(forms.Form):
    name=forms.CharField()
    message=forms.CharField(widget=forms.Textarea)
    widgets={
        'name':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter the name of the respective teacher'}),
        'message':forms.Textarea(attrs={'class':'form-control'}),
    }

classroom/views.py
from dataclasses import field
from locale import delocalize
from django.shortcuts import render
from django.urls import reverse,reverse_lazy
from django.views.generic import TemplateView,FormView,CreateView,ListView,DetailView,UpdateView,DeleteView
from classroom.models import Teacher
from classroom.forms import ContactForm
# password:dell
# username:dell
# Create your views here.
class HomeView(TemplateView):
    template_name='classroom/home.html'
class ThankYouView(TemplateView):
    template_name='classroom/thank_you.html'

class ContactFormView(FormView):
    form_class=ContactForm
    template_name='classroom/contact.html'
    
    # URL not a template.html
    success_url="/classroom/thank_you/"
    #what to do with the form
    def form_valid(self,form):
      print(form.cleaned_data)
      return super().form_valid(form)

class TeacherCreateView(CreateView):
    model=Teacher
    #model_form.html
    # .save()
    fields="__all__"
    success_url=reverse_lazy('classroom:list_teacher')

class TeacherListView(ListView):
    #model_list.html
    model=Teacher
    context_object_name="teacher_list"
class TeacherDetailView(DetailView):
    #RETURN ONLY ONE MODEL ENTRY PK
    #model_detail.html
    model=Teacher
    #PK-->{{teacher}}
class TeacherUpdateView(UpdateView):
    #SHARE model_form.html--PK
    model=Teacher
    fields="__all__"
    success_url=reverse_lazy('classroom:list_teacher')
class TeacherDeleteView(DeleteView):
    #Form--> Confirm Delete Button
    model=Teacher
    success_url=reverse_lazy('classsroom:list_teacher')

classroom/templates/classroom/contact.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>FEEDBACK</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">
        <style>
    .form-group{
        font-family: 'Nunito', sans-serif;
        height:100vh;
        width:100%;
        background-repeat:no-repeat;
background-image:url('{% static 'classroom/bg1.jpg' %}');
background-size:cover;
display:flex;
align-items:center;
justify-content:center;
flex-direction:column;
    }
    .o{
        border:2px solid white;
        background-color:white;
        height:54%;
        width:50%;
        display:flex;
    align-items:center;
    justify-content:center;
    flex-direction:column;
     }
   </style>
    </head>
    <body>
        <div class="form-group">
            <div class="o">
            <h1 >GIVE IN YOUR FEEDBACK</h1>
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-secondary">POST</button>
            </form></div></div>
    </body>
</html>

classroom/templates/classroom/home.html
{% load static %}
<style>
    .container{
        {% comment %} background-image: linear-gradient(to right,rgba(84, 2, 2, 0.966) 2%,#2b4ff1fb 100%); {% endcomment %}
    display:flex;
    flex-direction:column;
    width:100%;
    height:100%;
    align-items:center;
    justify-content:center;
    background-image:url('{% static 'classroom/bg.jpg' %}');
    background-repeat:no-repeat;
    background-size:cover;
}
.container li{
    margin:2%;
    padding:2%;
    display:flex;
    align-items:center;
    justify-content:center;
}
.container li a{
    text-decoration:none;
    font-family: 'Nunito', sans-serif;
}

</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">
<div class="container">
<h1 style="color:black; padding-top:1%"><i>WELCOME TO THE HOME PAGE</i></h1>
<ul>
    <li>
       <h2> <a href="{% url "classroom:contact" %}"  >FEEDBACK FORM</a></h2>
    </li>
    <li>
         <h2><a href="{% url "classroom:create_teacher" %}"  >CreateTeacher PageLink</a></h2>
    </li>
    <li>
       <h2> <a href="{% url "classroom:list_teacher" %}">ListTeacher PageLink</a></h2>
   </li>
   {% comment %} <li>
    <a href="{% url "classroom:detail_teacher" %}">DetailTeacher PageLink</a>
</li> {% endcomment %}
</ul>
</div>

classroom/templates/classroom/teacher_confirm.html
<h1>Are you sure you want to delete this teacher?</h1>
<h2>{{teacher}}</h2>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete">
</form>

classroom/templates/classroom/teacher_detail.html
<h1>Detail View for Teacher</h1>
{{teacher}}

classroom/templates/classroom/teacher_form.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>FEEDBACK</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Nunito&family=Oswald:wght@300&display=swap" rel="stylesheet">
        <style>
    .form-group{
        font-family: 'Nunito', sans-serif;
        height:100vh;
        width:100%;
        background-repeat:no-repeat;
background-image:url('{% static 'classroom/bg1.jpg' %}');
background-size:cover;
display:flex;
align-items:center;
justify-content:center;
flex-direction:column;
    }
    .form-group li a{
     text-decoration:none;
     font-family: 'Oswald', sans-serif;
     color:white;
 }
 .o{
    border:2px solid white;
    background-color:white;
    height:54%;
    width:50%;
    display:flex;
align-items:center;
justify-content:center;
flex-direction:column;
 }
   </style>
    </head>
    <body>
<div class="form-group">
 <div class="o">
<h1>Teacher Form</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>
</div>
</div>
</body>
</html>

classroom/templates/classroom/teacher_list.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>FEEDBACK</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">
        <style>
    .form-group{
        font-family: 'Nunito', sans-serif;
        height:100vh;
        width:100%;
        background-repeat:no-repeat;
background-image:url('{% static 'classroom/bg1.jpg' %}');
background-size:cover;
display:flex;
align-items:center;
justify-content:center;
flex-direction:column;
    }
    .form-group li a{
     text-decoration:none;
     font-family: 'Nunito', sans-serif;
     color:white;
 }
   </style>
    </head>
    <body>
        <div class="form-group">
<h1>List Of Teachers(List View)</h1>
<ul>
    {% for teacher in teacher_list %}
         {% comment %} teacher_list used above instead of objects_list by using context_object_name in views {% endcomment %}
    <li><a href="/classroom/teacher_detail/{{teacher.id}}">{{teacher.first_name}}  {{teacher.last_name}}</a>
    <ul>
         <li>
                <a href="/classroom/update_teacher/{{teacher.id}}">UPDATE INFO</a></li>
         </li>
    </ul>
    <ul>
</ul>
     {% endfor %}
</ul>
</div>
</body>
</html>

classroom/templates/classroom/thank_you.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>FEEDBACK</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Nunito&family=Oswald:wght@300&display=swap" rel="stylesheet">
        <style>
    .form-group{
        font-family: 'Nunito', sans-serif;
        height:100vh;
        width:100%;
        background-repeat:no-repeat;
background-image:url('{% static 'classroom/bg.jpg' %}');
background-size:cover;
display:flex;
align-items:center;
justify-content:center;
flex-direction:column;
    }
    .form-group li a{
     text-decoration:none;
     font-family: 'Oswald', sans-serif;
     color:white;
 }
 .o{
    border:2px solid white;
    background-color:white;
    height:54%;
    width:50%;
    display:flex;
align-items:center;
justify-content:center;
flex-direction:column;
 }
   </style>
    </head>
    <body>
<div class="form-group">
<h1>THANK YOU FOR YOUR RESPONSE!!!!!!!!</h1>
<a href="{% url "classroom:home" %}" style="text-decoration:none;color:black">Back</a>
</div>
</body>
</html>